import Decimal from 'decimal.js';

export function cfgCounters() {
    return (
        [

            {
                name: "Lemonade Stand",
                revenue: new Decimal(1.67),
                initialVisible: 1,
                owned: 1,
                initialCost: new Decimal(4),
                costGrowth: 1.07,
                boostPct: 0,
                boostMult: 0,
                isVisible: true,
                disabled: true,
            },
            {
                name: "Newspaper Delivery",
                revenue: new Decimal(20.00),
                initialVisible: 60,
                owned: 0,
                initialCost: new Decimal(60),
                costGrowth: 1.15,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },
            {
                name: "Car Wash",
                revenue: new Decimal(90.00),
                initialVisible: 540,
                owned: 0,
                initialCost: new Decimal(720),
                costGrowth: 1.14,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },
            {
                name: "Pizza Delivery",
                revenue: new Decimal(360),
                initialVisible: 4320,
                owned: 0,
                initialCost: new Decimal(8640),
                costGrowth: 1.13,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },
            {
                name: "Donut Shop",
                revenue: new Decimal(2160),
                initialVisible: 51840,
                owned: 0,
                initialCost: new Decimal(103680),
                costGrowth: 1.12,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },
            {
                name: "Shrimp Boat",
                revenue: new Decimal(6480),
                initialVisible: 622080,
                owned: 0,
                initialCost: new Decimal(1244160),
                costGrowth: 1.11,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },
            {
                name: "Hockey Team",
                revenue: new Decimal(19440),
                initialVisible: 7464960,
                owned: 0,
                initialCost: new Decimal(14929920),
                costGrowth: 1.10,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },
            {
                name: "Movie Studio",
                revenue: new Decimal(58320),
                initialVisible: 89579520,
                owned: 0,
                initialCost: new Decimal(179159040),
                costGrowth: 1.9,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },
            {
                name: "Bank",
                revenue: new Decimal(174960),
                initialVisible: 1074954240,
                owned: 0,
                initialCost: new Decimal(2149908480),
                costGrowth: 1.8,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },
            {
                name: "Oil Company",
                revenue: new Decimal(804816),
                initialVisible: 29668737024,
                owned: 0,
                initialCost: new Decimal(25798901760),
                costGrowth: 1.7,
                boostPct: 0,
                boostMult: 0,
                isVisible: false,
                disabled: true,
            },

        ]
    );
}

// export default cfgCounters;